### ISSUE TITLE
netbout-client integration tests get stuck at RtFriendsITCase

### ISSUE THREAD

**Issue by hs3180** [yegor256/netbout#791]
start a local netbout server:

    mvn clean install -Phit-refresh -Dport=8080

run netbout-client integration tests(at netbout-client directory):

    mvn clean verify -Dnetbout.token=xxx -Dnetbout.url=http://localhost:8080

then, it will get stuck like this:

    [INFO] --- maven-failsafe-plugin:2.17:integration-test (default) @ netbout-client ---
    [WARNING] useSystemClassloader setting has no effect when not forking
    [INFO] Failsafe report directory: /home/ubuntu/netbout/netbout-client/target/failsafe-reports
    [INFO] parallel='all', perCoreThreadCount=true, threadCount=8, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0, parallelOptimized=true
    
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------

it will be ok if you 
 * set the url to **http://www.netbout.com**

or
 * open **http://localhost:8080/?PsByFlag=fake-user&urn=urn:test:54321** and register a user named **alex**

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@hs3180 I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment]
@hs3180 thank you for reporting this, I added 15 mins to your acc, transaction `AP-09N90667A9921863J`

**Comment by karato** [comment]
@prahladyeri can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by prahladyeri** [comment]
@karato I'm presently occupied with [this](https://github.com/teamed/qulice/issues/526) issue, until at least tomorrow.

**Comment by prahladyeri** [comment]
@karato I've finished with issue 526, now you can assign this ticket to me. I'll checkout the `netbout` code and try to replicate this issue.

**Comment by prahladyeri** [comment]
@karato Yes, I can replicate this issue at my end. The freeze issue is caused by `maven-failsafe-plugin` when the `integration-test` goal is run. You can find this inside `/netbout-client/pom.xml`:

            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <netbout.token>${netbout.token}</netbout.token>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

Commenting this block of code will bypass the freezing, but obviously the integration testing won't be complete and the app won't run. The process happening in `integration-test` goal needs to be analyzed to see what its doing that is causing the goal to freeze. Of course, I have zero understanding of how `netbout` works at all at the code level! So, I'll need a lot more time to work on this.

**Comment by karato** [comment]
> @karato I'm presently occupied with [this](https://github.com/teamed/qulice/issues/526) issue, will look into this after it is solved.

@prahladyeri no need to inform me about the progress, let me know when it's done

**Comment by karato** [comment]
> @karato I've finished with issue 526, now you can assign this ticket to me. I'll checkout the `netbout` code and try to replicate this issue.

@prahladyeri we assign tickets according to our own algorithm, but thanks for asking

**Comment by prahladyeri** [comment]
@karato Raised [539](https://github.com/teamed/qulice/issues/539) for the `maven-failsafe-plugin` issue. Awaiting its resolution from there.

**Comment by hs3180** [comment]
@prahladyeri I may not explain this bug clearly. You could pass all tests if you skip `invitesAndKicksOff` in `RtFriendsITCase` or add a user named `alex` in netbout server. Your quest is to figure out why `invitesAndKicksOff` will get stuck when there is no one named `alex`.

**Comment by dmzaytsev** [comment]
@prahladyeri I agree with @hs3180 
it seems a problem in `invitesAndKicksOff`
the maven plugin doesn't related to this issue

**Comment by prahladyeri** [comment]
@dmzaytsev Thanks, I'll try to figure that out from `netbout` code and the maven scripts.
@hs3180 I'm looking into it.

**Comment by prahladyeri** [comment]
@hs3180 Indeed, the issue is in `invitesAndKicksOff()` method of `com.netbout.client.RtFriendsITCase` which is called in the verification goal.  Problem here is that `alex` user is hard-coded for testing this scenario. The code below assumes that `alex` user is registered and proceeds to invite that user:

        final User user = this.rule.get();
        final Alias alias = user.aliases().iterate().iterator().next();
        final Inbox inbox = alias.inbox();
        final Bout bout = inbox.bout(inbox.start());
        final String friend = "alex";
        System.out.println("inviting friend...");
        bout.friends().invite(friend);

So yes, the integration test appears to be designed to work only when the `alex` user is registered. Do you want to get this test redesigned so that it takes a variable from an `xml` file or something instead of the hard-coded `alex`?

**Comment by hs3180** [comment]
@prahladyeri There are actually two questions here. 
1. a hard-coded name in test case.
2. test case get stuck when invite a friend which doesn't exist.

Just show us your pull request, or your planned solution if you are not sure whether you understand requirements. Look at this http://www.yegor256.com/2014/10/07/stop-chatting-start-coding.html

**Comment by dmzaytsev** [comment]
@prahladyeri  RtFriendsITCase#invitesAndKicksOff() must not get stuck if a friend doesn't exists or any another reason.
A test method should raise an exception if something happened inside
a hard-coded name is another issue

**Comment by prahladyeri** [comment]
@hs3180 
Raised the pull request [891](https://github.com/yegor256/netbout/pull/891) as fix for this. Adding the parallel tests timeout fixes this. The build is presently failing, but I'm in the process of sorting it out.

**Comment by hs3180** [comment]
@prahladyeri 
it doesn't solve the problem mentioned in this ticket. if you think tests should timeout when there are freeze issues, raise a new ticket about that.

**Comment by prahladyeri** [comment]
@hs3180 How does it not solve the problem in this ticket? The issue is about `netbout-client` integration tests getting stuck and my fix certainly provides a workaround for that.

If you need RCA (Root Cause Analysis) of the RtFriendsITCase component, that could be raised a separate bug, but this one is solved.

**Comment by hs3180** [comment]
@prahladyeri It's fine if you can raise several new non-trivial tickets to solve these problems. But I can't close this ticket if you just let the tests timeout when get stuck.

**Comment by prahladyeri** [comment]
@hs3180 I've made a permanent fix for the build freeze issue by removing the `ReUser` wrapper class from `NbRule` test case. Please close if this resolves the issue.

**Comment by prahladyeri** [comment]
@hs3180 
Plz have a look at my fix. Either close this or let me know what else is needed.

**Comment by hs3180** [comment]
@prahladyeri thanks.
BTW: you can raise issues about hard-coded unit test and ReUser.

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks for the review

**Comment by karato** [comment]
@prahladyeri I added 10 mins to @elenavolokhova (for QA review) in transaction 73332895. Thanks a lot, I just topped your account for **30 mins**, transaction ID `73332907`, total time was 95 hours and 37 mins. +30 to your rating, your total score is [+75](http://www.netbout.com/b/36189?open=rating)
