### ISSUE TITLE
Netbout presented in Google Search in unfriendly way

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#878]
This is what shows when [searching for "netbout"](https://www.google.com/search?q=netbout):
![image](https://cloud.githubusercontent.com/assets/5467276/11867874/3ddfe4a4-a4b4-11e5-904f-89bf18cf84a6.png)

Netbout should have proper meta and title tags on main page, for example:
```
<title>Netbout | Private talks made easy</title>
<meta name="Netbout.com is a conversation-centric UI on demand, which is making software to help us communicate, instead of making us to communicate through software.">
```

**Comment by dmzaytsev** [comment]
@karato valid bug

**Comment by karato** [comment]
> @karato valid bug

@dmzaytsev I added `bug` tag to this ticket

**Comment by karato** [comment]
@mkordas since there is no milestone yet I set it to "3.1"

**Comment by karato** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `5676eb8490b4581f3c0000bc`

**Comment by karato** [comment]
@kitsook this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by kitsook** [comment]
@karato please see PR #969 

@dmzaytsev since the site is XML/XSLT based, i doubt if google or other web crawlers will pickup the meta tag.  for reference, see [how google indexed stateful.co](https://www.google.com/search?q=site%3astateful.co). it just so happen that stateful.co has a `documentation` tag that contains the description.  if this meta tag doesn't work, we can try to add a dummy tag for netbout's XML response to contain the description.

**Comment by dmzaytsev** [comment]
@kitsook Why we can't add `documentation` tag on netbout.com ?
the response from stateful.co below
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type='text/xsl' href='/xsl/index.xsl'?>
<page date="2016-01-24T11:44:30.213Z" ip="****" sla="24.340" ssl="false">
    <menu>home</menu>
    <documentation>&lt;h1&gt;Stateful Web Primitives&lt;/h1&gt;

&lt;p&gt;Stateful.co is a collection of web primitives, accessible
through web interface and RESTful API.&lt;/p&gt;
....
```

**Comment by kitsook** [comment]
@dmzaytsev yes we can.  assuming the web crawler is treating the response as xml, we can name the tag as `documentation` or whatever and it will parse the text within.

another possible way is to return fully processed html instead of xml/xslt.  i see in [RsPage.java](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/RsPage.java#L102) it now returns html if the browser is firefox.  We could do similar thing if the user-agent is [Googlebot](https://support.google.com/webmasters/answer/1061943?hl=en)

**Comment by dmzaytsev** [comment]
@kitsook let's try `documentation` tag first
there are a few crawlers,
not only google

**Comment by kitsook** [comment]
@mkordas PR #969 merged. please close this issue if appropriate. thx

**Comment by kitsook** [comment]
@mkordas ping

**Comment by mkordas** [comment]
@kitsook you should have been pinging me every couple of hours, sorry for delay, closing

**Comment by karato** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Looks good!

**Comment by karato** [comment]
> @karato Looks good!

@elenavolokhova thanks a lot ;)

**Comment by karato** [comment]
@kitsook just added 10 mins to @elenavolokhova (for QA), payment ID is `75940182`

Much obliged! I have added **30 mins** to your account in payment "AP-30U95834AC425133F", 142 hours and 54 mins spent

+30 to your rating, your total score is [+30](http://www.netbout.com/b/36293?open=rating)
